### ISSUE TITLE
C++ lexer is broken with spaces before semicolons

### ISSUE THREAD

**Issue by rumpelsepp** [rumpelsepp/rugments#15]
I seem to have come across an issue with c++ formatting, which results in
repetition of some elements when rendered.

I logged the issue with gitlab, where this was found, but they advised to
take it up with rugments as that is what they are using for syntax
highlighting.

Details of the issue can be found here -
https://gitlab.com/gitlab-org/gitlab-ce/issues/1356

Please let me know if you need any additional information,
Thanks for your time.

**Comment by stanhu** [comment]
I think this is fixed here:

https://github.com/jneen/rouge/pull/278

**Comment by rumpelsepp** [comment]
I'll bump a new release with this fix today. :+1:

**Comment by stanhu** [comment]
Thanks, Stefan, for the quick turnaround!
