### ISSUE TITLE
multiline comment is broken for all languages

### ISSUE THREAD

**Issue by qqshfox** [rumpelsepp/rugments#17]
example:

https://gitlab.com/libvirt/libvirt/blob/master/src/cpu/cpu_aarch64.c

![image](https://cloud.githubusercontent.com/assets/459733/6977248/4b3d12f4-d9ec-11e4-8e40-a5a35e098374.png)

**Comment by rumpelsepp** [comment]
I already spotted this. I think not "all languages" are broken, but C like languages.

**Comment by rumpelsepp** [comment]
there are indeed several problems; see #9 and https://gitlab.com/gitlab-org/gitlab-ce/issues/1495
