### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by jneen** [rumpelsepp/rugments#18]
Hi there!

I'm wondering if you're planning on pushing any of this back to mainline rouge?  It'd be a shame to duplicate so much effort.

**Comment by rumpelsepp** [comment]
As I mentioned here https://github.com/gitlabhq/gitlabhq/pull/8425#issuecomment-72381044, yes. Currently I am on a hard deadline with my master thesis, so unfortunately I am forced to "maintenance mode" only for now. You'll get pull request from me when I have less workload. :)

**Comment by jneen** [comment]
Ah ok, thanks!

**Comment by rumpelsepp** [comment]
The process has started: https://github.com/gitlabhq/gitlabhq/pull/9341
