### ISSUE TITLE
lisp parser breaks when used for GitLab's blame

### ISSUE THREAD

**Issue by ehuelsmann** [rumpelsepp/rugments#20]
Hi,

Also see the GitLab issue here: https://gitlab.com/gitlab-org/gitlab-ce/issues/1521 .

Ideally, I would submit the fix or help develop it, but can't without serious ruby coding help. As the maintainer of the common lisp code host https://GitLab.common-lisp.net, this issue his me pretty hard. If you want help by coaching me create the right patch, please join the #common-lisp.net channel on freenode.

**Comment by rumpelsepp** [comment]
I think this is now fixed, isn't it?
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/697

**Comment by stanhu** [comment]
Yes. :)
